### ISSUE TITLE
[Question] Custom SSH Port

### ISSUE THREAD

**Issue by dIELERx** [trustcrypto/onlykey-agent#16]
Hello Guys,

maybe this questions was already answered, but I could not find anything regarding custom ssh ports.

Most of my servers are configured with a custom SSH port, therefore onlykey-agent is not working as it always tried to connect via port 22. Is there anything I can do about that? Maybe some custom parameter? I could not find it in the help section.

Thanks and regards

dIELER

**Comment by TheRealKANi** [comment]
I was just looking for this feature and it is there, just not obvious..
'onlykey-agent  user@host:port'  generate key
'onlykey-agent -c user@host:port' connect
