### ISSUE TITLE
Source code of the python package lib-agent

### ISSUE THREAD

**Issue by ranfdev** [trustcrypto/onlykey-agent#23]
I'm writing an issue in this repo because the "homepage" link on [PyPi](https://pypi.org/project/lib-agent/) points here: 
http://github.com/onlykey/onlykey-agent, which is the old version of this repo.

In commit [b860bfce8863b657bcd1b44bf680af94d5c183c3](https://github.com/trustcrypto/onlykey-agent/commit/b860bfce8863b657bcd1b44bf680af94d5c183c3) most of the source code of `onlykey-agent` was replaced with a custom library, `lib-agent`.

By looking at the PyPi page, I can see `lib-agent` is licensed under the LGPLv3, but I can't find the source code anywhere.

Can you please upload the source code of `lib-agent`, or, if the code is already online, edit the link on PyPi, so that the `homepage` points to the actual source code?
Thank you

**Comment by romanz** [comment]
https://github.com/romanz/trezor-agent/tree/master/libagent

**Comment by ranfdev** [comment]
Mmm... But that's `libagent`not `lib-agent`.
`onlykey-agent` uses `lib-agent`, as stated in the `setup.py`
```py
install_requires=[
        'lib-agent>=0.14.2',
        'onlykey>=1.2.0'
    ],
```

Anyway, at the moment the actual content of the two packages is basically the same, so i'll stop nitpicking.

**Comment by onlykey** [comment]
@ranfdev Yes your right, when we released onlykey-agent the libagent did not yet support OnlyKey. That was just added so we released lib-agent which is pretty much the same source so we could support this until libagent is fully supported. If you want to take a look at that source it is here - https://github.com/onlykey/trezor-agent/tree/lib-agent-release
